name: CD
on:
  push:
    branches:
      - feat/merge-cd-prod-staging-v2
  workflow_dispatch:
    inputs:
      pull_number:
        description: Pull Request ID
        required: true
      environment:
        description: Environment
        default: staging
        required: true
      environment_variables:
        description: Additional Environment Variables
        required: false
env:
  DOCKER_BUILDKIT: "1"
  KUBECONFIG: ./kubeconfig.yaml
  REPOSITORY_NAME: archdaily
  NODE_VERSION: "8.11.0"
  PULL_NUMBER: ${{ github.event.inputs.pull_number }}
jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_EVENT_NAME
      - name: Set environment variables
        run: |
          echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_ENV
          echo "APP_NAME=$(echo ${{ github.repository}} | awk -F / '{print $2}')" >> $GITHUB_ENV
          echo "RAILS_ENV_LINE=$(echo ${{ github.event.inputs.environment_variables }} | sed -E 's/([a-zA-Z_=]+)/--set-string rails_env.\1/g')" >> $GITHUB_ENV
          echo "APP_ENV=$(if [ $GITHUB_EVENT_NAME = "workflow_dispatch" ]; then echo ${{ github.event.inputs.environment }}; else echo "production"; fi)" >> $GITHUB_ENV
      - name: Set release name
        run: echo "RELEASE_NAME=$(if [ $GITHUB_EVENT_NAME = "workflow_dispatch" ]; then echo $APP_NAME-pr-$PULL_NUMBER; else echo $APP_NAME; fi)" >> $GITHUB_ENV
      - name: Get PR data
        if: env.GITHUB_EVENT_NAME == 'workflow_dispatch'
        uses: octokit/request-action@v2.x
        id: get_pull_request
        with:
          route: GET /repos/${{ github.repository }}/pulls/${{ env.PULL_NUMBER }}
        env:
          GITHUB_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
      - name: Print pull request state
        if: env.GITHUB_EVENT_NAME == 'workflow_dispatch'
        run: echo ${{ fromJson(steps.get_pull_request.outputs.data).state }}
      - name: Check Pull Request state
        run: exit 1
        if: env.GITHUB_EVENT_NAME == 'workflow_dispatch' && fromJson(steps.get_pull_request.outputs.data).state != 'open'
      - name: Set branch name
        run: |
          echo "BRANCH_NAME=$(if [ $GITHUB_EVENT_NAME = "workflow_dispatch" ]; then echo ${{ fromJson(steps.get_pull_request.outputs.data).head.ref }}; else echo ${GITHUB_REF#refs/heads/}; fi)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}
          fetch-depth: 0
      - name: Setup git config
        run: |
          git config --global user.email "<>"
          git config --global user.name "The OPS Team"
      - name: Merge base branch
        if: env.GITHUB_EVENT_NAME == 'workflow_dispatch'
        run: |
          git merge origin/${{ fromJson(steps.get_pull_request.outputs.data).base.ref }}
      - name: Print Environment Variables
        run: |
          echo $SHORT_SHA
          echo $APP_NAME
          echo $RAILS_ENV_LINE
          echo $BRANCH_NAME
          echo $RELEASE_NAME
      - run: echo "The job has failed"
        if: failure()
