name: Test cron

on:
  push:
    branches:
      - master

  schedule:
    - cron: '*/5 * * * *'

env:
  APP_NAME: ${{ github.event.repository.name || "app" }}

jobs:
  test_cron:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: List files
        run: ls -lah

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Print APP_NAME
        run: |
          echo "$APP_NAME"
