name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      pull_number:
        description: Pull Request to Promote
        required: true
      environment:
        description: Environment
        default: staging
        required: true
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_pull_request
        with:
          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.inputs.pull_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
      - name: Print ref and base branch
        run: |
          echo "Head Ref branch ${{ fromJson(steps.get_pull_request.outputs.data).head.ref }}"
          echo "Base branch ${{ fromJson(steps.get_pull_request.outputs.data).base.ref }}"