name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      pull_number:
        description: Pull Request to Promote
        required: true
      environment:
        description: Environment
        default: staging
        required: true
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_pull_request
        with:
          route: GET /repos/:repository/pulls/:pull_number
          pull_number: ${{ github.event.inputs.pull_number }}
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
      - name: Print ref and base branch
        env:
          HEAD_REF: ${{ fromJson(steps.get_pull_request.outputs.data).head.ref }}
          BASE_REF: ${{ fromJson(steps.get_pull_request.outputs.data).base.ref }}
        run: |
          echo "Ref branch $HEAD_REF"
          echo "Ref branch $BASE_REF"
