name: Merge PR base branch.
on:
  workflow_dispatch:
    inputs:
      pull_number:
        description: Pull Request to Promote
        required: true
      environment:
        description: Environment
        default: staging
        required: true
jobs:
  merge_base_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR data
        uses: octokit/request-action@v2.x
        id: get_pull_request
        with:
          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.inputs.pull_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ fromJson(steps.get_pull_request.outputs.data).head.ref }}
          fetch-depth: 0
      - name: Setup git config
        run: |
          git config --global user.email "ops@archdaily.com"
          git config --global user.name "The OPS Team"
      - name: Merge base branch
        run: |
          git merge origin/${{ fromJson(steps.get_pull_request.outputs.data).base.ref }}