name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      pull_request:
        description: 'Pull request to promote'
        required: true
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Pull request to promote ${{ github.event.inputs.pull_request }}!"
        echo "Branch to promote ${{ env.GITHUB_REF }}"