name: Add staging deploy instructions message.

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print github object
        run: echo ${{ toJson(github) }}
