name: Add staging deployment instructions

on:
  pull_request:
    types:
      - opened
      - reopened
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create staging deployment instructions
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          body: |
            Add here the tavo's comment:
            `AFD_HOST=xxx KENNETH_HOST=xxx`
          reactions: 'rocket'