name: Add staging deployment instructions

on:
  pull_request:
    types:
      - opened
      - reopened
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install jq

      - name: Print event json
        run: cat "$GITHUB_EVENT_PATH" | jq -M .

      - name: Create staging deployment instructions
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          reactions: eyes, hooray